name: Generate Keystore

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate keystore
        run: |
          keytool -genkeypair -v \
            -keystore jimi-release-key.jks \
            -alias jimi_key \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -storepass "JimiSecure123!" \
            -keypass "JimiSecure123!" \
            -dname "CN=Jimi, OU=Jimi, O=Jimi, L=City, S=State, C=IN"

      - name: Upload keystore as artifact
        uses: actions/upload-artifact@v4
        with:
          name: jimi-keystore
          path: jimi-release-key.jks
